name: nlp-imdb-sentiment

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.11
  - pip

  # Core scientific stack
  - numpy
  - pandas
  - scipy

  # NLP / ML (modelo cl√°sico)
  - scikit-learn

  # Visualization / notebooks
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel

  # Utilities
  - pyyaml
  - tqdm
  - rich
  - joblib

  # Testing / quality
  - pytest

  # Deep learning
  - pytorch
  - torchvision
  - torchaudio

  # Pip-only packages
  - pip:
      - datasets
      - transformers
      - evaluate
      - accelerate
      - sentencepiece
      - pre-commit
